removing -v

diff --git a/client/create_customer b/client/create_customer
--- a/client/create_customer
+++ b/client/create_customer
@@ -17,6 +17,12 @@
 
 LI_SERVER='li.mmcgrath.libra.mmcgrath.net'
 
+function quit {
+    echo
+    echo -e $1 1>&2
+    exit
+}
+
 function print_help {
     echo "Usage: $0"
     echo "Create a new libra user."
@@ -66,4 +72,4 @@ ssh_key=$(awk '{ print $2 }' ~/.ssh/libra_id_rsa.pub)
 TMPDIR=$(mktemp -d --suffix=libra)
 curl -s --data-urlencode "username=${username}" --data-urlencode "email=${email}" --data-urlencode "ssh_key=${ssh_key}" "http://$LI_SERVER/create_customer.php" > $TMPDIR/debug.log 2>&1 || quit "Creation failed.  See $TMPDIR/debug.log for more information"
 
-grep -q 'return: 0' $TMPDIR/debug.log && quit "Creation failed. See $TMPDIR/debug.log for more information"
+grep -q 'return: 0' $TMPDIR/debug.log || quit "Creation failed. See $TMPDIR/debug.log for more information"
