change default mysql charset to utf-8

diff --git a/cartridges/mysql-5.1/info/hooks/configure b/cartridges/mysql-5.1/info/hooks/configure
--- a/cartridges/mysql-5.1/info/hooks/configure
+++ b/cartridges/mysql-5.1/info/hooks/configure
@@ -106,7 +106,7 @@ chown $user_id $APP_HOME/.env/OPENSHIFT_DB_USERNAME $APP_HOME/.env/OPENSHIFT_DB_
 
 ## Setup user
 echo "drop database test;
-create database \`${application}\`;" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" > /dev/null || error "Failed to create ${application}" 188
+create database \`${application}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" > /dev/null || error "Failed to create ${application}" 188
 
 echo "                                  
 delete from user;
