changing order of operations for mysql creation

diff --git a/cartridges/mysql-5.1/info/hooks/configure b/cartridges/mysql-5.1/info/hooks/configure
--- a/cartridges/mysql-5.1/info/hooks/configure
+++ b/cartridges/mysql-5.1/info/hooks/configure
@@ -234,12 +234,12 @@ echo "export OPENSHIFT_DB_MYSQL_51_DUMP_REMOVE='rm -rf /tmp/mysql_dump_snapshot.
 echo "export OPENSHIFT_DB_MYSQL_51_RESTORE='$MYSQL_DIR/mysql_restore.sh'" > $APP_HOME/.env/OPENSHIFT_DB_MYSQL_51_RESTORE
 
 # Setup user
+echo "create database ${application};" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" > /dev/null || error "Failed to create ${application}" 188
+
 echo "                                  
 delete from user;
 grant all on *.* to 'admin'@'$IP' identified by '$password' with grant option;
 flush privileges;" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to setup initial root user" 187
-
-echo "create database ${application};" | mysql -u root -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to create ${application}" 188
 
 echo "CLIENT_RESULT: "
 echo "CLIENT_RESULT: Mysql 5.1 database added.  Please make note of these credentials:"
