move updates, add pre_build

diff --git a/cartridges/mysql-5.1/info/hooks/move b/cartridges/mysql-5.1/info/hooks/move
--- a/cartridges/mysql-5.1/info/hooks/move
+++ b/cartridges/mysql-5.1/info/hooks/move
@@ -49,10 +49,15 @@ uuid=$3
 setup_basic_vars
 
 CART_INFO_DIR=$CART_DIR/embedded/mysql-5.1/info
+source ${CART_INFO_DIR}/lib/util
+
+MYSQL_DIR="$APP_HOME/mysql-5.1/"
 
 . $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
 IP=$OPENSHIFT_INTERNAL_IP
 
+. $APP_HOME/.env/OPENSHIFT_DB_HOST
+ORIG_DB_HOST=$OPENSHIFT_DB_HOST
 echo "export OPENSHIFT_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_DB_HOST
 
 . $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
@@ -61,9 +66,13 @@ then
     echo "export OPENSHIFT_DB_URL='mysql://admin@$IP:3306/'" > $APP_HOME/.env/OPENSHIFT_DB_URL
 else
     echo "export OPENSHIFT_DB_URL='mysql://admin:$OPENSHIFT_DB_PASSWORD@$IP:3306/'" > $APP_HOME/.env/OPENSHIFT_DB_URL
+    
+start_mysql
+
+    echo "
+UPDATE user SET Host='$IP' WHERE Host='$ORIG_DB_HOST';
+flush privileges;" | mysql -u admin -h $ORIG_DB_HOST --password="$OPENSHIFT_DB_PASSWORD" -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to setup root user with new ip" 187
+
+stop_mysql
+
 fi
-
-$CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $IP
-$CART_INFO_DIR/bin/deploy_httpd_proxy.sh $application $namespace $uuid $IP
-
-restart_httpd_graceful
