mysql and mongo move

diff --git a/cartridges/mysql-5.1/info/hooks/move b/cartridges/mysql-5.1/info/hooks/move
--- a/cartridges/mysql-5.1/info/hooks/move
+++ b/cartridges/mysql-5.1/info/hooks/move
@@ -16,7 +16,7 @@
 # General Public License and may only be used or replicated with the express
 # permission of Red Hat, Inc.
 
-# Deploy httpd proxy
+# Move the app to a new ip
 
 # Exit on any errors
 set -e
@@ -56,23 +56,21 @@ MYSQL_DIR="$APP_HOME/mysql-5.1/"
 . $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
 IP=$OPENSHIFT_INTERNAL_IP
 
+. $APP_HOME/.env/OPENSHIFT_DB_PORT
+
 . $APP_HOME/.env/OPENSHIFT_DB_HOST
 ORIG_DB_HOST=$OPENSHIFT_DB_HOST
 echo "export OPENSHIFT_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_DB_HOST
 
 . $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
-if [ "$OPENSHIFT_DB_PASSWORD" = "NOT_AVAILABLE" ]
-then
-    echo "export OPENSHIFT_DB_URL='mysql://admin@$IP:3306/'" > $APP_HOME/.env/OPENSHIFT_DB_URL
-else
-    echo "export OPENSHIFT_DB_URL='mysql://admin:$OPENSHIFT_DB_PASSWORD@$IP:3306/'" > $APP_HOME/.env/OPENSHIFT_DB_URL
+. $APP_HOME/.env/OPENSHIFT_DB_USERNAME
     
 start_mysql
 
     echo "
 UPDATE user SET Host='$IP' WHERE Host='$ORIG_DB_HOST';
-flush privileges;" | mysql -u admin -P $OPENSHIFT_DB_PORT -h $IP --password="$OPENSHIFT_DB_PASSWORD" -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to setup root user with new ip" 187
+flush privileges;" | mysql -u $OPENSHIFT_DB_USERNAME -P $OPENSHIFT_DB_PORT -h $IP --password="$OPENSHIFT_DB_PASSWORD" -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to setup root user with new ip" 187
 
 stop_mysql
 
-fi
+set_app_info "Connection URL: mysql://$IP:3306/"
diff --git a/cartridges/mysql-5.1/info/hooks/post-move b/cartridges/mysql-5.1/info/hooks/post-move
--- a/cartridges/mysql-5.1/info/hooks/post-move
+++ b/cartridges/mysql-5.1/info/hooks/post-move
@@ -16,7 +16,7 @@
 # General Public License and may only be used or replicated with the express
 # permission of Red Hat, Inc.
 
-# Deploy httpd proxy
+# Cleanup app after moving to a new ip
 
 # Exit on any errors
 set -e
@@ -48,25 +48,23 @@ uuid=$3
 
 setup_basic_vars
 
-CART_INFO_DIR=$CART_DIR/embedded/mongodb-2.0/info
+CART_INFO_DIR=$CART_DIR/embedded/mysql-5.1/info
 source ${CART_INFO_DIR}/lib/util
 
-MONGODB_DIR="$APP_HOME/mongodb-2.0/"
-
-. $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST
-ORIG_DB_HOST=$OPENSHIFT_NOSQL_DB_HOST
+MYSQL_DIR="$APP_HOME/mysql-5.1/"
 
 . $APP_HOME/.env/OPENSHIFT_INTERNAL_IP
 IP=$OPENSHIFT_INTERNAL_IP
 
-. $APP_HOME/.env/OPENSHIFT_NOSQL_DB_PASSWORD
-. $APP_HOME/.env/OPENSHIFT_NOSQL_DB_USERNAME
+. $APP_HOME/.env/OPENSHIFT_DB_PORT
 
-echo "export OPENSHIFT_NOSQL_DB_HOST='$IP'" > $APP_HOME/.env/OPENSHIFT_NOSQL_DB_HOST
-echo "export OPENSHIFT_NOSQL_DB_URL='mongodb://$OPENSHIFT_NOSQL_DB_USERNAME:$OPENSHIFT_NOSQL_DB_PASSWORD@$IP:27017/'" > $APP_HOME/.env/OPENSHIFT_NOSQL_DB_URL
+. $APP_HOME/.env/OPENSHIFT_DB_PASSWORD
+. $APP_HOME/.env/OPENSHIFT_DB_USERNAME
+    
+start_mysql
 
-pushd "$MONGODB_DIR" > /dev/null
-sed -i "s,$ORIG_DB_HOST,$IP," $MONGODB_DIR/etc/mongodb.conf
-popd > /dev/null
+    echo "
+DELETE FROM user WHERE Host<>'$IP';
+flush privileges;" | mysql -u $OPENSHIFT_DB_USERNAME -P $OPENSHIFT_DB_PORT -h $IP --password="$OPENSHIFT_DB_PASSWORD" -S "${MYSQL_DIR}/socket/mysql.sock" mysql > /dev/null || error "Failed to setup root user with new ip" 187
 
-set_app_info "Connection URL: mongodb://$IP:27017/"
+stop_mysql
