Notify when a start or stop times out.

diff --git a/node/scripts/init/libra b/node/scripts/init/libra
--- a/node/scripts/init/libra
+++ b/node/scripts/init/libra
@@ -103,32 +103,44 @@ then
     echo 1 > /proc/sys/net/ipv6/conf/default/disable_ipv6
 fi
 
+return_output() {
+    if [ "$1" ]; then
+	echo >> "$1" 2>&1
+	cat "$1" | sed -e "s#\[  OK  \]#\[  ${GREEN}OK${NORM}  \]#" -e "s#\[FAILED\]#\[${RED}FAILED${NORM}\]#"
+	rm -f "$1"
+    fi
+}
+
+return_terminate() {
+    print_column -n 59 "Timeout $1..."
+    echo "[${RED}FAILED${NORM}]"
+    exit 1
+}
+
 startuser() {
     # USERNAME=$1
     local OUTFILE=$(mktemp /var/run/stickshift/stickshift_init-startuser-$1.XXXXXXXX)
+    trap "return_terminate $1 $OUTFILE" USR1
     echo "Starting $1..." >> $OUTFILE 2>&1
-    for APPNAME in `userapps $1`
-    do
-        startapp $1 $APPNAME >> $OUTFILE 2>&1
-    done
-    echo >> $OUTFILE 2>&1
-
-    cat $OUTFILE | sed -e "s#\[  OK  \]#\[  ${GREEN}OK${NORM}  \]#" -e "s#\[FAILED\]#\[${RED}FAILED${NORM}\]#"
-    rm $OUTFILE
+    ( for APPNAME in `userapps $1`
+      do
+          startapp $1 $APPNAME >> $OUTFILE 2>&1
+      done ) &
+    wait
+    return_output $OUTFILE
 }
 
 stopuser() {
     # USERNAME=$1
     local OUTFILE=$(mktemp /var/run/stickshift/stickshift_init-stopuser-$1.XXXXXXXX)
+    trap "return_terminate $1 $OUTFILE" USR1
     echo "Stopping $1..." >> $OUTFILE 2>&1
-    for APPNAME in `userapps $1`
-    do
-        stopapp $1 $APPNAME >> $OUTFILE 2>&1
-    done
-    echo >> $OUTFILE 2>&1
-
-    cat $OUTFILE | sed -e "s#\[  OK  \]#\[  ${GREEN}OK${NORM}  \]#" -e "s#\[FAILED\]#\[${RED}FAILED${NORM}\]#"
-    rm $OUTFILE
+    ( for APPNAME in `userapps $1`
+      do
+          stopapp $1 $APPNAME >> $OUTFILE 2>&1
+      done ) &
+    wait
+    return_output $OUTFILE
 }
 
 setuppam(){
@@ -194,7 +206,7 @@ start() {
     echo "Starting Libra Services: "
     echo
 
-    echo `libra_users` | xargs -d' ' -I{} -n 1 -P $numparallel /usr/bin/timeout $timeout /etc/init.d/libra startuser {}
+    echo `libra_users` | xargs -d' ' -I{} -n 1 -P $numparallel /usr/bin/timeout -s USR1 $timeout /etc/init.d/libra startuser {}
 
     echo -n "All Libra services started"
     [ $GROUP_RETVAL -eq 0 ] && touch ${lockfile}
@@ -207,7 +219,7 @@ stop() {
     echo "Stopping Libra Services: "
     echo
 
-    echo `libra_users` | xargs -d' ' -I{} -n 1 -P $numparallel /usr/bin/timeout $timeout /etc/init.d/libra stopuser {}
+    echo `libra_users` | xargs -d' ' -I{} -n 1 -P $numparallel /usr/bin/timeout -s USR1 $timeout /etc/init.d/libra stopuser {}
 
     echo -n "All Libra services stopped"
     [ $GROUP_RETVAL -eq 0 ] && touch ${lockfile}
@@ -221,7 +233,7 @@ restart() {
     echo "Restarting Libra Services: "
     echo
 
-    echo `libra_users` | xargs -d' ' -I{} -n 1 -P $numparallel /usr/bin/timeout $timeout /etc/init.d/libra restartuser {}
+    echo `libra_users` | xargs -d' ' -I{} -n 1 -P $numparallel /usr/bin/timeout -s USR1 $timeout /etc/init.d/libra restartuser {}
 
     echo -n "All Libra services restarted"
     [ $GROUP_RETVAL -eq 0 ] && touch ${lockfile}
