List proxies, add and remove proxies command.  Included locking and wait for state transition to prevent haproxy from getting stepped on.

diff --git a/node/scripts/init/libra-proxy b/node/scripts/init/libra-proxy
--- a/node/scripts/init/libra-proxy
+++ b/node/scripts/init/libra-proxy
@@ -33,10 +33,135 @@ check() {
     $exec -c -V -f $cfgfile
 }
 
+getaddr() {
+  ip -4 addr show dev eth0 scope global | sed -r -n '/inet/ { s/^.*inet ([0-9\.]+).*/\1/; p }' | head -1
+}
+
 fixaddr() {
     # Fix eth0's address in case it was changed by the cloud provider
-    baddr=`ip -4 addr show dev eth0 scope global | sed -r -n '/inet/ { s/^.*inet ([0-9\.]+).*/\1/; p }' | head -1`
+    baddr=`getaddr`
     sed -i -r -e '/^[^\#]*bind/ { /127\.[0-9\.]+:/ b; s/([0-9\.]+):/'"$baddr"':/ }' $cfgfile
+}
+
+
+listproxies() {
+  # List out the defined proxies
+  sed -n -r -e 's/^listen ([0-9]+:[0-9\.]+\:[0-9])/\1/; t yi; d; : yi p' haproxy.cfg
+}
+
+
+rollcfg() {
+  # If proxy is running, roll the configuration and block till done
+  if [ -f $lockfile ]; then
+
+    $exec -c -q -f $cfgfile
+    if [ $? -ne 0 ]; then
+      echo "Error: Proxy configuration is corrupt."
+      return 1
+    fi
+
+    oldpid=$( cat $pidfile )
+
+    if ! [ "/proc/$oldpid/exe" -ef "$exec"  ]; then
+      echo "libra-proxy has crashed."
+      return 1
+    fi
+
+    $exec -D -f $cfgfile -p $pidfile -sf "$oldpid"
+    retv=$?
+    while [ "/proc/$oldpid/exe" -ef "$exec" ]; do
+      usleep 500000
+    done
+  fi
+  return 0
+}
+
+delproxy() {
+  # Remove a proxy port from the configuration file
+  # Usage delproxy [proxport]
+  proxport="$1"
+
+  if ! [ "$proxport" -ge 16384 -a "$proxport" -le 65535 ]; then
+    # also catch non-numeric args
+    return 1
+  fi
+
+  sed -i -e '/^listen '"$proxport"':/,/^#End '"$proxport"'/ d' $cfgfile
+  return $?
+}
+
+delproxy_r() {
+  lockfile ${cfgfile}.lock
+  delproxy "$1"
+  retcode=$?
+  if [ $retcode != 0 ]; then
+    echo "Error: Bad proxy configuration."
+  else
+    rollcfg
+    retcode=$?
+  fi
+  rm -f ${cfgfile}.lock
+  return $retcode
+}
+
+addproxy() {
+  # Add a proxy port to the configuration file overwriting
+  # any existing proxy defined for the same port.
+  # Usage addproxy [proxport] [ip] [port]
+  proxport="$1"
+  dstip="$2"
+  port="$3"
+
+  if ! [ "$proxport" -ge 16384 -a "$proxport" -le 65535 ]; then
+    echo "Proxy port must be an integer between 16384 and 65535"
+    return 1
+  fi
+
+  if ! [ "$port" -ge 1 -a "$port" -le 65535 ]; then
+    echo "Dest port must be an integer between 16384 and 65535"
+    return 1
+  fi
+
+  ipbytes=( `echo "$dstip" | sed -e 's/\./ /g'` )
+  if [ ${#ipbytes} -ne 3 ]; then
+    echo "Dest addr must be a valid IP address."
+    return 1
+  fi
+
+  for byt in "${ipbytes[@]}"; do
+    if ! [ "$byt" -ge 0 -a "$byt" -le 255 ]; then
+      echo "Dest addr must be a valid IP address."
+      return 1
+    fi
+  done
+
+  baddr=`getaddr`
+
+  delproxy $proxport
+
+  cat <<EOF >> $cfgfile
+listen $proxport:$dstip:$port
+    mode tcp
+    bind $baddr:$proxport
+    server $proxport $dstip:$port
+# End $proxport:$dstip:$port
+EOF
+
+  return $?
+}
+
+addproxy_r() {
+  lockfile ${cfgfile}.lock
+  addproxy "$1" "$2" "$3"
+  retcode=$?
+  if [ $retcode != 0 ]; then
+    echo "Error: Bad proxy configuration."
+  else
+    rollcfg
+    retcode=$?
+  fi
+  rm -f ${cfgfile}.lock
+  return $retcode
 }
 
 start() {
@@ -113,7 +238,16 @@ case "$1" in
     condrestart|try-restart)
   	[ ! -f $lockfile ] || restart
 	;;
+    listproxies)
+        listproxies
+        ;;
+    delproxy)
+        delproxy_r "$2"
+        ;;
+    addproxy)
+        addproxy_r "$2" "$3" "$4"
+        ;;
     *)
-        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
+        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload|listproxies|delproxy [proxport]| addproxy [proxport] [ip] [port]}"
         exit 2
 esac
