dont reject start if selinux is disabled

diff --git a/backend/scripts/libra b/backend/scripts/libra
--- a/backend/scripts/libra
+++ b/backend/scripts/libra
@@ -19,13 +19,19 @@ lockfile=/var/lock/subsys/libra
 RETVAL=0
 GROUP_RETVAL=0
 
-if ! ( runcon | grep -q s0-s0:c0.c1023 )
-then
-    echo 1>&2
-    echo "ERROR: incorrect selinux range - please rerun with:" 1>&2
-    echo "runcon -l s0-s0:c0.c1023 $0" 1>&2
-    echo 1>&2
-    exit 243
+selinuxenabled
+if [ $? -eq 1 ]
+then 
+    if ! ( runcon | grep -q s0-s0:c0.c1023 )
+    then
+        echo 1>&2
+        echo "ERROR: incorrect selinux range - please rerun with:" 1>&2
+        echo "runcon -l s0-s0:c0.c1023 $0" 1>&2
+        echo 1>&2
+        exit 243
+    else
+        echo "WARNING: Running with selinux disabled" 1>&2
+    fi
 fi
 
 start() {
