Typeless gear changes for US 2105
Changes for US 2105

Changes for US 2110 namespace cart envs

Fix for rhc-idler.

Fix for rhc-restorer.

Use namespaced environment variables in zend-5.6 cart

Env var support for phpmo, rockmongo

Fix libra init script.

Fix rhcsh to not use deprecated env vars.

Fixup parameter.

Fix DB vars in rhcsh.

Migrations (WIP).

Add create_standard_cart_env_vars to zend-5.6 configure

Update zendserver_gui_config.sh to use correct dir.

Fix trap user test.

Remove redundant env var creation now handled by util

Call create_standard_cart_env_vars in metrics-0.1 configure

Change metrics-0.1 to use namespaced env vars

Add migration for ruby-1.8 and ruby-1.9 carts

Fix conflict breakage.

Removing old env vars from metrics-0.1

Fix conflicts.

Removing namespaced env vars from metrics-0.1

Zend env fixes

First pass env var fix for phpmoadmin

Zend env fixes

Phpmoadmin typeless fixes (not yet tested)

Refactor app_ctl.sh for metrics-0.1

Refactor app_ctl.sh for metrics-0.1

Refactor app_ctl.sh for metrics-0.1

Refactor app_ctl.sh for metrics-0.1

Refactor app_ctl.sh for metrics-0.1

Refactor app_ctl.sh for metrics-0.1

Refactor app_ctl.sh for metrics-0.1

Remove Watchman dependency on *_CART_DIR

Fix ctl_all in rhcsh.

Typeless phpmoadmin

Typeless rockmongo

Typeless fixes for metrics

Run dir cleanup

Refactor libra script for typeless-gears

Refactor migrate.rb for typeless-gears

Refactor migrate.rb for typeless-gears

Zend deconfigure remove rm_app_dir

Refactor migrate.rb for typeless-gears

Add restore scenario for cartridge-idler.feature

Refactor idle/restore tests to scenario outlines

Add ruby-1.8 to idle/restore tests

Add ruby-1.9 to idle/restore tests

Add php-5.3 to idle/restore tests

Add node.js to idle/restore tests

Add python-2.3 to idle/restore tests

Add jboss to idle/restore tests

Add test for auto-restore to cartridge_idler.feature

Refactor rhc-idler to use get_installed_framework_carts

Refactor rhc-restorer to use get_installed_framework_carts

Update node scripts for type-less gears

Update node scripts for type-less gears (fix)

Restore scaling tests (WIP)

Fix snapshot for zend.

Restore scaling tests (WIP, perl-5.10 fails)

Restore scaling tests

Fixes for BZ859388

remove verbose option

migration WIP

Namespaced environment variables

Create namespaced IP environment variables as needed

Add extended tests for rockmongo embedding

Migrations for frameworks/dbs/metrics/cron.

Refactor extended rockmongo test to work independently of framework cart

Remove singleton tag from extended rockmongo tests

Migrations for embedded carts.

Add missing call to create namespaced network env vars.

Add extended tests for rhcsh

HA Proxy migrations.

Correct syntax

Change stepdef name in trap-user-extended

Add JBoss and Zend to migration list

Move haproxy scaled db migration script.

Migration fixes.

Migration fixes

Replace rm_rf(..) with rm(..) if exists?(..) to better report errors
Remove phpmoadmin from rockmongo migration

Remove .env/.uservars/OPENSHIFT_NOSQL_DB_* during migration

Remove dependency on OPENSHIFT_GEAR_TYPE

Added comment about METRICS environment variables

migrate OPENSHIFT_NOSQL_DB_PROXY_PORT

More fixes for Jenkins migration

Fixed Jenkins job migration

Fix for proxy port migration.

Fix migrate.rb for jboss eap

diff --git a/node/scripts/bin/rhc-node-application b/node/scripts/bin/rhc-node-application
--- a/node/scripts/bin/rhc-node-application
+++ b/node/scripts/bin/rhc-node-application
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Survey the character of an application
 #
@@ -33,11 +33,10 @@ function user_app_type() {
     _APPTYPE=`cat ${_HOMEDIR}/git/${2}.git/description | cut -d' ' -f1`
     if [ "$_APPTYPE" != "Unnamed" ]
     then
-	echo $_APPTYPE
+      echo $_APPTYPE
     else
-	#echo "WARNING: Unnamed Application: update git description" >&2
-	_APPDIR=`dirname ${_HOMEDIR}/*/$2`
-	basename $_APPDIR
+      #echo "WARNING: Unnamed Application: update git description" >&2
+      ls $_HOMEDIR |grep -v 'app-root|git' |sed '$!s/$/, /' |tr -d '\n'
     fi
 }
 
@@ -45,12 +44,6 @@ function user_app_git() {
     # USERNAME=$1
     # APPNAME=$2
     echo `homedir $1`/git/${2}.git
-}
-
-function user_app_workspace() {
-    # USERNAME=$1
-    # APPNAME=$2
-    echo `homedir $1`/${2}
 }
 
 function valid_app() {
@@ -61,14 +54,15 @@ function valid_app() {
     # directory
     if [ ! -d `user_app_git $1 $2` ]
     then
-	echo "ERROR: not a valid application: `user_app_git $1 $2` does not exist" >&2
-	return 1
+      echo "ERROR: not a valid application: `user_app_git $1 $2` does not exist" >&2
+      return 1
     fi
 
-    if [ ! -d `user_app_workspace $1 $2` ]
+    cartridges=`ls \`homedir $1\` |egrep -v 'app-root|git'`
+    if [ -z "$cartridges" ]
     then
-	echo "ERROR: not a valid application: `user_app_workspace $1 $2` does not exist" >&2
-	return 1
+      echo "ERROR: not a valid application: $1 $2 contains no cartridges" >&2
+      return 1
     fi
 
     return 0
@@ -77,13 +71,14 @@ function valid_app() {
 function user_app_disk_space() {
     # USERNAME=$1
     # APPNAME=$2
-    du -s `homedir $1`/$2 | cut -f1
+    _home=`homedir $1`
+    du -s `ls -d $_home/* |egrep -v 'app-root|git'` | awk '{total=total+$1} END {print total}'
 }
 
 function user_app_repo_disk_space() {
     # USERNAME=$1
     # APPNAME=$2
-    du -s `homedir $1`/$2/repo | cut -f1
+    du -s `homedir $1`/app-root/runtime/repo | cut -f1
 }
 
 function user_app_git_disk_space() {
@@ -95,13 +90,13 @@ function user_app_git_disk_space() {
 function user_app_log_disk_space() {
     # USERNAME=$1
     # APPNAME=$2
-    du -s `homedir $1`/$2/logs | cut -f1
+    du -s `ls -d \`homedir $1\`/*/logs/* |egrep -v 'app-root|git'` | awk '{total=total+$1} END {print total}'
 }
 
 function user_app_data_disk_space() {
     # USERNAME=$1
     # APPNAME=$2
-    du -s `homedir $1`/$2/data | cut -f1
+    du -s `homedir $1`/app-root/data | cut -f1
 }
 
 # ============================================================================
@@ -166,17 +161,21 @@ echo
 # largest log files
 # insert an = to prevent splitting
 echo log file sizes 
-for FSPEC in `bigfiles \`user_app_workspace $USERNAME $APPNAME\`/logs | tr ' ' '='`
+for dir in `ls -d \`homedir $USERNAME\`/*/logs |egrep -v 'app-root|git'`
 do
-    # this is truely ugly.  It needs to be formatted
-    echo " " `echo '  ' $FSPEC | tr '=' ' '`
+    echo $dir
+    for FSPEC in `bigfiles $dir | tr ' ' '='`
+    do
+      # this is truely ugly.  It needs to be formatted
+      echo " " `echo '  ' $FSPEC | tr '=' ' '`
+    done
 done
 echo
 
 # largest log files
 # insert an = to prevent splitting
 echo data file sizes 
-for FSPEC in `bigfiles \`user_app_workspace $USERNAME $APPNAME\`/data | tr ' ' '='`
+for FSPEC in `bigfiles \`homedir $USERNAME\`/app-root/data | tr ' ' '='`
 do
     # this is truely ugly.  It needs to be formatted
     echo " " `echo '  ' $FSPEC | tr '=' ' '`
@@ -186,7 +185,7 @@ echo
 # largest log files
 # insert an = to prevent splitting
 echo app large files
-for FSPEC in `bigfiles \`user_app_workspace $USERNAME $APPNAME\`/repo | tr ' ' '='`
+for FSPEC in `bigfiles \`homedir $USERNAME\`/app-root/repo | tr ' ' '='`
 do
     # this is truely ugly.  It needs to be formatted
     echo " " `echo '  ' $FSPEC | tr '=' ' '`
