fixing path order

diff --git a/cartridges/jenkins-client-1.4/info/hooks/configure b/cartridges/jenkins-client-1.4/info/hooks/configure
--- a/cartridges/jenkins-client-1.4/info/hooks/configure
+++ b/cartridges/jenkins-client-1.4/info/hooks/configure
@@ -115,16 +115,17 @@ mcs_level=`${CART_DIR}/li-controller/info/bin/mcs_level $uid`
 # Setup Environment Variables
 #
 echo "export OPENSHIFT_CI_TYPE='jenkins-1.4'" > $APP_HOME/.env/OPENSHIFT_CI_TYPE
+echo "export PATH=\$PATH:${CART_INFO_DIR}/bin/" > $APP_HOME/.env/PATH_JENKINS_CLIENT
 
 . $APP_HOME/.env/OPENSHIFT_DATA_DIR
 . $APP_HOME/.env/OPENSHIFT_APP_NAME
 . $APP_HOME/.env/JENKINS_URL
 
-/usr/bin/wget -q ${JENKINS_URL}jnlpJars/jenkins-cli.jar -O "$OPENSHIFT_DATA_DIR/jenkins-cli.jar" || error "Could not download ${JENKINS_URL}jnlpJars/jenkins-cli.jar" 157
+/usr/bin/wget --no-check-certificate -q ${JENKINS_URL}jnlpJars/jenkins-cli.jar -O "$OPENSHIFT_DATA_DIR/jenkins-cli.jar" || error "Could not download ${JENKINS_URL}jnlpJars/jenkins-cli.jar" 157
 
 # Maybe allow cartridges to create their own jenkins job
 runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level ${CART_INFO_DIR}/bin/jenkins-cli create-job '${OPENSHIFT_APP_NAME}-build'" < $CART_INFO_DIR/configuration/template.xml
 
 echo "CLIENT_RESULT: "
-echo "CLIENT_RESULT: Jenkins Client 1.4 has been added to $OPENSHIFT_APP_NAME:"
+echo "CLIENT_RESULT: Jenkins Client 1.4 has been added to: $OPENSHIFT_APP_NAME"
 echo "CLIENT_RESULT: Job URL: ${JENKINS_URL}job/${OPENSHIFT_APP_NAME}-build/"
