US2378: Zend Server Cartridge Packaging

diff --git a/cartridges/zend-5.6/info/hooks/configure b/cartridges/zend-5.6/info/hooks/configure
--- a/cartridges/zend-5.6/info/hooks/configure
+++ b/cartridges/zend-5.6/info/hooks/configure
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Creates a zend instance
+# Creates a php instance
 
 # Exit on any errors
 set -e
@@ -24,34 +24,36 @@ done
 
 [ $# -eq 4 -o $# -eq 3 ] || print_help
 
+cartridge_type="zend-5.6"
 source "/etc/stickshift/stickshift-node.conf"
-app_type="zend-5.6"
 source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util
 
 setup_configure "$1" $2 $3 $4
+disable_cgroups
 
-check_app_dir_doesnt_exist
+check_cartridge_dir_doesnt_exist
 
 # Repo
 if [ ! -d $git_url ]; then
 	clone_external_git_repo $application $user_id $group_id $uuid $git_url
 else
-	clone_git_repo $application $user_id $group_id $uuid "zend-5.6"
+	clone_git_repo $application $user_id $group_id $uuid "zend 5.6"
 fi
 
 #
 # Create the core of the application
 #
-
-mkdir -p "$APP_DIR"
-pushd "$APP_DIR" > /dev/null
+create_cartridge_instance_dir "$cartridge_type"
+create_app_dir_symlink "$cartridge_type"
+ZENDCART_INSTANCE_DIR=$(get_cartridge_instance_dir "$cartridge_type")
+pushd "$ZENDCART_INSTANCE_DIR" > /dev/null
 create_standard_app_dirs
 mkdir conf conf.d logs sessions
 mkdir -p phplib/pear/{docs,ext,php,cache,cfg,data,download,temp,tests,www}
 ln -s /usr/lib64/httpd/modules modules
 ln -s /etc/httpd/conf/magic conf/magic
-sed -e "s,TEMPLATE_SET_ME_SESSION_SAVE_PATH,$APP_DIR/sessions/," \
-    -e "s,TEMPLATE_SET_ME_UPLOAD_TMP_DIR,$APP_DIR/tmp/," $CART_CONF_DIR/php.ini > $APP_DIR/conf/php.ini 
+sed -e "s,TEMPLATE_SET_ME_SESSION_SAVE_PATH,$ZENDCART_INSTANCE_DIR/sessions/," \
+    -e "s,TEMPLATE_SET_ME_UPLOAD_TMP_DIR,$ZENDCART_INSTANCE_DIR/tmp/," $CART_CONF_DIR/php.ini > $ZENDCART_INSTANCE_DIR/conf/php.ini
 popd > /dev/null
 
 #
@@ -62,35 +64,54 @@ IP=`find_open_ip $uid $uuid`
 $CART_INFO_DIR/bin/deploy_httpd_config.sh $application $uuid $IP
 $CART_INFO_DIR/bin/zendserver_gui_config.sh $application $uuid $IP
 
-create_app_ctl_script "$app_type"
+create_app_ctl_script "$cartridge_type"
+
+#copy over zen config files
+ZEND_USER_FILES="/usr/libexec/stickshift/cartridges/${cartridge_type}/files/user-files"
+echo "ZEND_USER_FILES ${ZEND_USER_FILES}"
+$CART_INFO_DIR/bin/zend_configure_filesystem_on_gear.sh ${ZEND_USER_FILES} ${ZENDCART_INSTANCE_DIR} ${user_id} ${group_id} ${IP} || error "Failed to copy files to cartridge directory" 121
+run_as_user "$CART_INFO_DIR/bin/zend_configure_filesystem_on_gear.sh ${ZEND_USER_FILES} ${ZENDCART_INSTANCE_DIR} ${user_id} ${group_id} ${IP}" || error "Failed to create symlinks in sandbox namespace" 121
 
 # Pear requires a special pearrc file, this is that file:
-pear config-create "$APP_DIR"/phplib/pear/ "$APP_HOME"/.pearrc > /dev/null 2>&1
-pear -c "$APP_HOME"/.pearrc config-set php_ini "$APP_DIR"/conf/php.ini > /dev/null 2>&1
-observe_setup_var_lib_file "$APP_HOME"/.pearrc
+#pear config-create "$ZENDCART_INSTANCE_DIR"/phplib/pear/ "$APP_HOME"/.pearrc > /dev/null 2>&1
+#pear -c "$APP_HOME"/.pearrc config-set php_ini "$ZENDCART_INSTANCE_DIR"/conf/php.ini > /dev/null 2>&1
+#pear -c "$APP_HOME"/.pearrc config-set auto_discover 1 > /dev/null 2>&1
+#observe_setup_var_lib_file "$APP_HOME"/.pearrc
 
 populate_repo_dir
 
 secure_app_dir
 
+secure_cart_instance_dir
+
 secure_conf_dirs
 
 observe_setup_app_and_git_dirs
+
+observe_setup_cart_instance_dir
 
 #
 # Create environment variables
 #
 create_standard_env_vars
+create_standard_env_uservars
 create_standard_network_env_vars
 create_standard_repo_dir_env_var
 create_standard_path_env_var
 
-run_as_user "$CART_INFO_DIR/bin/zend_configure_filesystem.sh" || error "Failed to set filesystem in pam namespace" 121
+observe_setup_env_uservars_dir
 
-#
-# Start the server
-#
-start_app
+if [ ! -d $git_url ]; then
+    #
+    # Resolve app dependencies for template
+    #
+    resolve_application_dependencies $uuid $application &
+else
+    #
+    # Start the server
+    #
+    start_app
+fi
 
 #
 # Create virtualhost definition for apache
@@ -98,6 +119,5 @@ start_app
 export CART_INFO_DIR
 $CARTRIDGE_BASE_PATH/abstract/info/bin/deploy_httpd_proxy.sh $application $namespace $uuid $IP
 $CART_INFO_DIR/bin/zend_deploy_httpd_proxy.sh $application $namespace $uuid $IP
-
 restart_httpd_graceful
-
+enable_cgroups
