added disk quota check on /

diff --git a/node/tools/bin/li-accept-node b/node/tools/bin/li-accept-node
--- a/node/tools/bin/li-accept-node
+++ b/node/tools/bin/li-accept-node
@@ -25,7 +25,7 @@ else
 	RESULT=`getsebool $NAME`
 	if [ "$RESULT" != "$NAME --> $VALUE" ]
         then
-	    echo "FAIL: selinux boolean $NAME should be $VALUE"
+	    echo "FAIL: selinux boolean $NAME should be $VALUE" >&2
 	    STATUS=$(($STATUS + 1))
         fi
     done
@@ -40,13 +40,23 @@ do
     PKGSTATUS=`rpm -q $PKGNAME`
     if echo $PKGSTATUS | grep "not installed" >/dev/null
     then
-	echo "FAIL: package $PKGNAME is not installed"
+	echo "FAIL: package $PKGNAME is not installed" >&2
 	STATUS=$(($STATUS + 1))
     fi 
 done
 #
 # Check services
 #
+SERVICES="qppid mcollective cgconfig cgred httpd"
+for SVCNAME in $SERVICES
+do
+    service $SVCNAME status > /dev/null 2>&1
+    if [ $? != 0 ]
+    then
+	echo "FAIL: service $SVCNAME not running"
+	STATUS=$(($STATUS + 1))
+    fi
+done
 
 #
 # Check kernel settings
@@ -56,7 +66,7 @@ MINSEM=512
 SEMCOUNT=`sysctl kernel.sem | cut -f4`
 if [ "$SEMCOUNT" -lt "$MINSEM" ]
 then
-    echo "ERROR: kernel.sem semaphores too low: $SEMCOUNT < $MINSEM"
+    echo "FAIL: kernel.sem semaphores too low: $SEMCOUNT < $MINSEM" >&2
     STATUS=$(($STATUS + 1))
 fi
 
@@ -72,6 +82,12 @@ fi
 #
 # Check quotas
 #
+QUOTASTAT=`quotaon -u -p / 2>&1`
+if [ "$QUOTASTAT" != "user quota on / (/dev/xvda1) is on" ]
+then
+    echo "FAIL: quotas are not enabled on / (/dev/xvda)" >&2
+    STATUS=$(($STATUS + 1))
+fi
 
 echo $STATUS ERRORS
 exit $STATUS
