make deconfigure less error prone

diff --git a/cartridges/wsgi-3.2.1/info/hooks/deconfigure b/cartridges/wsgi-3.2.1/info/hooks/deconfigure
--- a/cartridges/wsgi-3.2.1/info/hooks/deconfigure
+++ b/cartridges/wsgi-3.2.1/info/hooks/deconfigure
@@ -18,9 +18,6 @@
 
 # Destroys http instance
 
-# Exit on any errors
-set -e
-
 if [ -f '/etc/libra/node.conf' ]
 then
     . /etc/libra/node.conf
@@ -60,7 +57,7 @@ function destroy_repo {
     uuid="$2"
     CUSTOMER_HOME="${libra_dir}/${uuid}"
 
-    if [ ! -d $CUSTOMER_HOME ]; then echo "ERROR: Customer ${uuid} not found!  Please create." 1>&2; exit 2; fi
+    if [ ! -d $CUSTOMER_HOME ]; then echo "ERROR: Customer ${uuid} not found!  Please create." 1>&2; fi
 
     GIT_DIR=$CUSTOMER_HOME/git/$application.git
     rm -rf $GIT_DIR || error "Could not remove ${application}" 108
@@ -96,9 +93,9 @@ destroy_repo $application $uuid
 # Create http base for application, every app gets its own apache instance
 #
 
-[ ! -d "$APP_DIR" ] && error "${application} does not exist" 138
+[ ! -d "$APP_DIR" ] && echo "${application} does not exist" 1>&2
 
-runuser --shell /bin/sh "$uuid" $APP_DIR/${application}_ctl.sh stop || error "Failed to stop ${application}" 140
+runuser --shell /bin/sh "$uuid" $APP_DIR/${application}_ctl.sh stop || echo "Failed to stop ${application}" 1>&2
 
 range_one=$(echo $IP | awk -F\. '{ print $3 }')
 range_two=$(echo $IP | awk -F\. '{ print $4 }')
@@ -117,5 +114,5 @@ runcon -l s0-s0:c0.c1023 rm -rf "$APP_DIR"
 #
 # Remove virtualhost definition for apache
 #
-rm -rf /etc/httpd/conf.d/${uuid}_${namespace}_${application}.conf || error "Could not remove apache definition" 156
-/sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || error "Failed to restart master httpd, please contact support" 120
+rm -rf /etc/httpd/conf.d/${uuid}_${namespace}_${application}.conf || echo "Could not remove apache definition" 1>&2
+/sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful || echo "Failed to restart master httpd, please contact support" 1>&2
