customer -> application rename in cartridges

diff --git a/cartridges/jbossas-7.0/info/hooks/configure b/cartridges/jbossas-7.0/info/hooks/configure
--- a/cartridges/jbossas-7.0/info/hooks/configure
+++ b/cartridges/jbossas-7.0/info/hooks/configure
@@ -72,9 +72,9 @@ namespace=`basename $2`
 application="$1"
 uuid=$3
 
-CUSTOMER_HOME="$libra_dir/$uuid/"
+APP_HOME="$libra_dir/$uuid/"
 # The location of the application jboss setup
-APP_DIR="$CUSTOMER_HOME/$application"
+APP_DIR="$APP_HOME/$application"
 [ -d "$APP_DIR" ] && error "${application}.  Please destroy then recreate, or pick a new name" 132
 
 # Redirect the configure script output for debugging
@@ -129,21 +129,21 @@ function create_repo {
     user_id=$2
     group_id=$3
     c_val=$4
-    CUSTOMER_HOME="${libra_dir}/${uuid}"
+    APP_HOME="${libra_dir}/${uuid}"
 
-    if [ ! -d $CUSTOMER_HOME ]; then echo "ERROR: Customer ${uuid} not found!  Please create." 1>&2; exit 2; fi
+    if [ ! -d $APP_HOME ]; then echo "ERROR: Application ${uuid} not found!  Please create." 1>&2; exit 2; fi
 
-    GIT_DIR=$CUSTOMER_HOME/git/$application.git
-    mkdir -p "$CUSTOMER_HOME/git"
+    GIT_DIR=$APP_HOME/git/$application.git
+    mkdir -p "$APP_HOME/git"
     git clone --bare /usr/libexec/li/cartridges/${jboss_version}/info/data/git_template.git $GIT_DIR
     echo "jbossas 7.x application '$application'" > $GIT_DIR/description
-    cat <<__EOF__ > $CUSTOMER_HOME/git/$application.git/hooks/post-receive
+    cat <<__EOF__ > $APP_HOME/git/$application.git/hooks/post-receive
 rm -rf $APP_DIR/repo/*
 git archive --format=tar HEAD | (cd $APP_DIR/repo && tar xf -)
 # Reload httpd here maybe?
 __EOF__
 
-    chmod 0755 $CUSTOMER_HOME/git/$application.git/hooks/post-receive
+    chmod 0755 $APP_HOME/git/$application.git/hooks/post-receive
     chown $user_id.$group_id -R $GIT_DIR
     # Secure the hooks dir
     chown root.root -R $GIT_DIR/hooks
diff --git a/cartridges/rack-1.1/info/hooks/deconfigure b/cartridges/rack-1.1/info/hooks/deconfigure
--- a/cartridges/rack-1.1/info/hooks/deconfigure
+++ b/cartridges/rack-1.1/info/hooks/deconfigure
@@ -58,11 +58,11 @@ function error {
 function destroy_repo {
     application="$1"
     uuid="$2"
-    CUSTOMER_HOME="${libra_dir}/${uuid}"
+    APP_HOME="${libra_dir}/${uuid}"
 
-    if [ ! -d $CUSTOMER_HOME ]; then echo "ERROR: Customer ${uuid} not found!  Please create." 1>&2; exit 2; fi
+    if [ ! -d $APP_HOME ]; then echo "ERROR: Application ${uuid} not found!  Please create." 1>&2; exit 2; fi
 
-    GIT_DIR=$CUSTOMER_HOME/git/$application.git
+    GIT_DIR=$APP_HOME/git/$application.git
     rm -rf $GIT_DIR || echo "Could not remove ${application}" 1>&2
 }
 
@@ -96,8 +96,8 @@ namespace=`basename $2`
 application="$1"
 uuid=$3
 
-CUSTOMER_HOME="$libra_dir/$uuid/"
-APP_DIR="$CUSTOMER_HOME/$application"
+APP_HOME="$libra_dir/$uuid/"
+APP_DIR="$APP_HOME/$application"
 
 #
 # Destroy git app repo
