updated mcs_level generation for app accounts > 522

diff --git a/cartridges/jbossas-7.0/info/hooks/configure b/cartridges/jbossas-7.0/info/hooks/configure
--- a/cartridges/jbossas-7.0/info/hooks/configure
+++ b/cartridges/jbossas-7.0/info/hooks/configure
@@ -173,7 +173,7 @@ function create_repo {
     application="$1"
     user_id=$2
     group_id=$3
-    c_val=$4
+    mcs_level=$4
 
     if [ ! -d $APP_HOME ]; then echo "ERROR: Application ${uuid} not found!  Please create." 1>&2; exit 2; fi
 
@@ -255,7 +255,7 @@ group_id=$(id -g "$uuid") || error "Could not find user $uuid ($namespace)" 135
 # Create git app repo
 #
 uid=$(id -u "$uuid")
-c_val="c$(($uid/1023)),c$(($uid%1023))"
+mcs_level=`${CART_DIR}/li-controller/info/bin/mcs_level $uid`
 
 #
 # Find an open localhost IP
@@ -304,7 +304,7 @@ sed -i "s/{app_name}/$application/g" "$APP_JBOSS"/standalone/configuration/stand
 popd > /dev/null
 
 # Repo
-create_repo $application $user_id $group_id $c_val
+create_repo $application $user_id $group_id $mcs_level
 
 # Build the standalone.conf file
 echo "Creating standalone.conf..."
@@ -362,7 +362,7 @@ chown $user_id.$group_id -R $APP_DIR || error "Failed to chown new application s
 chown root.root -R "$APP_DIR/${application}_ctl.sh"
 chown $user_id.$group_id -R "$APP_DIR/${jboss_version}/standalone"
 chown -R $user_id.$group_id $M2_DIR
-chcon -t libra_var_lib_t -l s0:$c_val -R "$APP_HOME/git/" "$APP_DIR"
+chcon -t libra_var_lib_t -l $mcs_level -R "$APP_HOME/git/" "$APP_DIR"
 
 #
 # Create environment variables
@@ -385,8 +385,8 @@ echo "export PATH=$JBOSS_CARTRIDGE_ROOT/info/bin/:$CART_DIR/abstract-httpd/info/
 # Start the server
 #
 cd $APP_DIR
-runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh start" || error "Failed to start ${application}" 121
-#GIT_DIR="$GIT_DIR" runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l s0:$c_val $GIT_DIR/hooks/post-receive" || error "Failed to start ${application}" 121
+runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $APP_DIR/${application}_ctl.sh start" || error "Failed to start ${application}" 121
+#GIT_DIR="$GIT_DIR" runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $GIT_DIR/hooks/post-receive" || error "Failed to start ${application}" 121
 
 #
 # Create virtualhost definition for apache
diff --git a/cartridges/jenkins-1.4/info/hooks/deconfigure b/cartridges/jenkins-1.4/info/hooks/deconfigure
--- a/cartridges/jenkins-1.4/info/hooks/deconfigure
+++ b/cartridges/jenkins-1.4/info/hooks/deconfigure
@@ -40,6 +40,8 @@ else
     exit 3
 fi
 
+CART_DIR=${CART_DIR:=/usr/libexec/li/cartridges}
+
 function print_help {
     echo "Usage: $0 app-name namespace uuid"
 
@@ -101,7 +103,7 @@ then
 fi
 
 uid=$(id -u "$uuid")
-c_val="c$(($uid/1023)),c$(($uid%1023))"
+mcs_level=`${CART_DIR}/li-controller/info/bin/mcs_level $uid`
 
 #
 # OpenShift values so they can be used:
@@ -112,7 +114,7 @@ do
 done
 
 jenkins_pid=$(/bin/cat ${OPENSHIFT_RUN_DIR}/jenkins.pid)
-runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l s0:$c_val $OPENSHIFT_APP_CTL_SCRIPT stop" || echo "Failed to stop ${OPENSHIFT_APP_NAME}" 1>&2
+runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l $mcs_level $OPENSHIFT_APP_CTL_SCRIPT stop" || echo "Failed to stop ${OPENSHIFT_APP_NAME}" 1>&2
 
 for i in {1..12}
 do
