move context to libra service and configure

diff --git a/cartridges/jbossas-7.0/info/hooks/configure b/cartridges/jbossas-7.0/info/hooks/configure
--- a/cartridges/jbossas-7.0/info/hooks/configure
+++ b/cartridges/jbossas-7.0/info/hooks/configure
@@ -270,11 +270,12 @@ then
     exit 1
 fi
 
-if whoami | grep -q root
+if whoami | grep -q root || ! runcon | grep 'system_r:libra_t:s0:$c_val'
 then
-    echo "Please don't run script as root, try:"
-    echo "runuser --shell /bin/sh $uuid $APP_DIR/${application}_ctl.sh"
-    echo
+    echo 1>&2
+    echo "Please run script in the correct context, try:" 1>&2
+    echo "runuser --shell /bin/sh \"$uuid\" -c \"runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh\"" 1>&2
+    echo 2>&1
     exit 15
 fi
 
@@ -297,7 +298,7 @@ case "\$1" in
             echo -n " - Application is disabled"
             exit 0
         else
-            runcon -t libra_t -l s0:$c_val $JBOSS_BIN_DIR/standalone.sh 1>&2 >${TMP_DIR}/${application}.log &
+            $JBOSS_BIN_DIR/standalone.sh 1>&2 >${TMP_DIR}/${application}.log &
             PROCESS_ID=\$!
             echo \$PROCESS_ID > \$JBOSS_PID_FILE
         fi
@@ -336,13 +337,8 @@ chown root.root -R "$APP_DIR/${application}_ctl.sh"
 chown $user_id.$group_id -R "$APP_DIR/${jboss_version}/standalone"
 chcon -t libra_var_lib_t -l s0:$c_val -R "$APP_DIR"
 cd $APP_DIR
-# Check if the incoming contex is correct. Useful for running script directly for testing.
-if ! ( runcon | grep -q system_r:libra_initrc_t )
-then
-    runcon -r system_r -t libra_initrc_t runuser --shell /bin/sh "$uuid" "$APP_DIR/${application}_ctl.sh" start || error "Failed to start ${application}" 121
-else
-    runuser --shell /bin/sh "$uuid" "$APP_DIR/${application}_ctl.sh" start || error "Failed to start ${application}" 121
-fi
+# Check if the incoming context is correct. Useful for running script directly for testing.
+runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh start" || error "Failed to start ${application}" 121
 
 #
 # Create virtualhost definition for apache
diff --git a/cartridges/rack-1.1/info/hooks/configure b/cartridges/rack-1.1/info/hooks/configure
--- a/cartridges/rack-1.1/info/hooks/configure
+++ b/cartridges/rack-1.1/info/hooks/configure
@@ -90,8 +90,8 @@ function find_open_ip {
     uuid=$2
     for host_ip in `seq 1 127`
     do
-	a=`address $uid $host_ip`
-	new_ip=`dotted_quad $a`
+  a=`address $uid $host_ip`
+  new_ip=`dotted_quad $a`
         if ! grep -qe '^Listen '$new_ip':8080$' $(find /var/lib/libra/$uuid/ -maxdepth 4 -mindepth 4 -name libra.conf) /etc/sysconfig/network
         then
             echo $new_ip
@@ -142,15 +142,43 @@ function create_repo {
     popd
 
     echo "rack 1.1 application '$application'" > $GIT_DIR/description
+    cat <<EOF > $GIT_DIR/hooks/pre-receive
+# Stop the app
+$APP_DIR/${application}_ctl.sh stop
+EOF
+
     cat <<EOF > $GIT_DIR/hooks/post-receive
+USING_BUNDLER=false
+if [ -d '$APP_DIR/tmp/.bundle' ]
+then
+  USING_BUNDLER=true
+  rm -rf '$APP_DIR/tmp/.bundle' '$APP_DIR/tmp/vendor'
+  mv '$APP_DIR/deploy/.bundle' '$APP_DIR/tmp/.bundle'
+  mv '$APP_DIR/deploy/vendor' '$APP_DIR/tmp/vendor'
+fi
+
 rm -rf $APP_DIR/deploy/*
 git archive --format=tar HEAD | (cd $APP_DIR/deploy && tar xf -)
 
-# Reload passenger
-touch $APP_DIR/deploy/tmp/restart.txt
+if \$USING_BUNDLER
+then
+  mv '$APP_DIR/tmp/.bundle' '$APP_DIR/deploy/.bundle'
+  mv '$APP_DIR/tmp/vendor' '$APP_DIR/deploy/vendor'
+fi
+
+if [ -f '$APP_DIR/deploy/Gemfile.lock' ]
+then
+  # Update/install necessary rubygems
+  pushd $APP_DIR/deploy > /dev/null
+  bundle install --deployment
+  popd > /dev/null
+fi
+
+# Start the app
+$APP_DIR/${application}_ctl.sh start
 EOF
 
-    chmod 0755 $APP_HOME/git/$application.git/hooks/post-receive
+    chmod 0755 $APP_HOME/git/$application.git/hooks/post-receive $APP_HOME/git/$application.git/hooks/pre-receive
     chown $user_id.$group_id -R $GIT_DIR
     # Secure the hooks dir
     chown root.root -R $GIT_DIR/hooks
@@ -277,11 +305,11 @@ then
     exit 1
 fi
 
-if whoami | grep -q root
+if whoami | grep -q root || ! runcon | grep 'system_r:libra_t:s0:$c_val'
 then
     echo 1>&2
-    echo "Please don't run script as root, try:" 1>&2
-    echo "runuser --shell /bin/sh $uuid $APP_DIR/${application}_ctl.sh" 1>&2
+    echo "Please run script in the correct context, try:" 1>&2
+    echo "runuser --shell /bin/sh \"$uuid\" -c \"runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh\"" 1>&2
     echo 2>&1
     exit 15
 fi
@@ -295,11 +323,11 @@ case "\$1" in
             echo -n " - Application is disabled" 1>&2
             exit 0
         else
-            runcon -t libra_t -l s0:$c_val /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/rack-1.1/info/configuration/etc/conf/httpd_nolog.conf -k \$1
+            /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/rack-1.1/info/configuration/etc/conf/httpd_nolog.conf -k \$1
         fi
     ;;
     restart|graceful|graceful-stop|stop)
-        runcon -t libra_t -l s0:$c_val /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/rack-1.1/info/configuration/etc/conf/httpd_nolog.conf -k \$1
+        /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/rack-1.1/info/configuration/etc/conf/httpd_nolog.conf -k \$1
     ;;
     status)
         echo "Coming soon"
@@ -317,7 +345,7 @@ chown $user_id.$group_id -R $APP_DIR || error "Failed to chown new application s
 chown root.root -R "$APP_DIR/${application}_ctl.sh" "$APP_DIR/conf" "$APP_DIR/conf.d"
 chown root.root "$APP_DIR"
 chcon -t libra_var_lib_t -l s0:$c_val -R "$APP_DIR"
-runuser --shell /bin/sh "$uuid" "$APP_DIR/${application}_ctl.sh" start || error "Failed to start ${application}" 121
+runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh start" || error "Failed to start ${application}" 121
 
 #
 # Create virtualhost definition for apache
diff --git a/cartridges/wsgi-3.2/info/hooks/configure b/cartridges/wsgi-3.2/info/hooks/configure
--- a/cartridges/wsgi-3.2/info/hooks/configure
+++ b/cartridges/wsgi-3.2/info/hooks/configure
@@ -265,11 +265,11 @@ then
     exit 1
 fi
 
-if whoami | grep -q root
+if whoami | grep -q root || ! runcon | grep 'system_r:libra_t:s0:$c_val'
 then
     echo 1>&2
-    echo "Please don't run script as root, try:" 1>&2
-    echo "runuser --shell /bin/sh $uuid $APP_DIR/${application}_ctl.sh" 1>&2
+    echo "Please run script in the correct context, try:" 1>&2
+    echo "runuser --shell /bin/sh \"$uuid\" -c \"runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh\"" 1>&2
     echo 2>&1
     exit 15
 fi
@@ -282,11 +282,11 @@ case "\$1" in
             echo -n " - Application is disabled" 1>&2
             exit 0
         else
-            runcon -t libra_t -l s0:$c_val /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/wsgi-3.2/info/configuration/etc/conf/httpd_nolog.conf -k \$1
+            /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/wsgi-3.2/info/configuration/etc/conf/httpd_nolog.conf -k \$1
         fi
     ;;
     restart|graceful|graceful-stop|stop)
-        runcon -t libra_t -l s0:$c_val /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/wsgi-3.2/info/configuration/etc/conf/httpd_nolog.conf -k \$1
+        /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/wsgi-3.2/info/configuration/etc/conf/httpd_nolog.conf -k \$1
     ;;
     status)
         echo "Coming soon"
@@ -301,7 +301,7 @@ chown $user_id.$group_id -R $APP_DIR || error "Failed to chown new application s
 chown root:root -R "$APP_DIR/${application}_ctl.sh" "$APP_DIR/conf" "$APP_DIR/conf.d"
 chown root:root "$APP_DIR"
 chcon -t libra_var_lib_t -l s0:$c_val -R "$APP_DIR"
-runuser --shell /bin/sh "$uuid" "$APP_DIR/${application}_ctl.sh" start || error "Failed to start ${application}" 121
+runuser --shell /bin/sh "$uuid" -c "runcon -t libra_t -l s0:$c_val $APP_DIR/${application}_ctl.sh start" || error "Failed to start ${application}" 121
 
 #
 # Create virtualhost definition for apache
