improving jenkins artifacts

diff --git a/build/devenv b/build/devenv
--- a/build/devenv
+++ b/build/devenv
@@ -195,17 +195,25 @@ mkdir -p /tmp/rhc/junit
 
     def download_artifacts(hostname)
       print "Downloading logs and screenshots..."
-      
-      `rm -rf rhc/log; mkdir -p rhc/log/; pushd rhc/log > /dev/null; mkdir site broker mcollective system screenshots selenium jbossas broker-profiler coverage; popd > /dev/null`
+      ssh(hostname, %{
+if [ -d /tmp/rhc ]
+then
+      rm -rf /tmp/rhc/**/*_repo
+fi
+}, 120, true)
+      `rm -rf rhc/log; mkdir -p rhc/log/; pushd rhc/log > /dev/null; mkdir -p site broker mcollective system screenshots selenium jbossas broker-profiler coverage; popd > /dev/null`
       scp_from(hostname, "/tmp/rhc/*", "rhc/log")
-      scp_from(hostname, "/var/www/stickshift/site/httpd/logs/*", "rhc/log/site")
+      scp_from(hostname, "/var/www/stickshift/site/httpd/logs/access_log", "rhc/log/site/access_log.log")
+      scp_from(hostname, "/var/www/stickshift/site/httpd/logs/error_log", "rhc/log/site/error_log.log")
       scp_from(hostname, "/var/www/stickshift/site/log/*", "rhc/log/site")
-      scp_from(hostname, "/var/www/stickshift/broker/httpd/logs/*", "rhc/log/broker")
+      scp_from(hostname, "/var/www/stickshift/broker/httpd/logs/access_log", "rhc/log/broker/access_log.log")
+      scp_from(hostname, "/var/www/stickshift/broker/httpd/logs/error_log", "rhc/log/broker/error_log.log")
       scp_from(hostname, "/var/www/stickshift/broker/log/*", "rhc/log/broker")
       scp_from(hostname, "/var/log/mcollective.*", "rhc/log/mcollective")
-      scp_from(hostname, "/var/log/httpd/*", "rhc/log/system")
-      scp_from(hostname, "/var/log/messages", "rhc/log/system")
-      scp_from(hostname, "/var/log/dmesg", "rhc/log/system")
+      scp_from(hostname, "/var/log/httpd/access_log", "rhc/log/system/access_log.log")
+      scp_from(hostname, "/var/log/httpd/error_log", "rhc/log/system/error_log.log")
+      scp_from(hostname, "/var/log/messages", "rhc/log/system/messages.log")
+      scp_from(hostname, "/var/log/dmesg", "rhc/log/system/dmesg.log")
       scp_from(hostname, "/tmp/rhc/screenshots/*", "rhc/log/screenshots")
       scp_from(hostname, "/root/li-test/selenium/output/*", "rhc/log/selenium")
       scp_from(hostname, "/var/lib/stickshift/*/*/jbossas-7/standalone/tmp/*.log", "rhc/log/jbossas")
@@ -295,22 +303,25 @@ if [ -d /tmp/rhc ]
 then
     if #{backup}
     then
-        if `ls /tmp/rhc/run_* > /dev/null`
+        if `ls /tmp/rhc/run_* > /dev/null 2>&1`
         then
             rm -rf /tmp/rhc_previous_runs
-            mkdir /tmp/rhc_previous_runs
+            mkdir -p /tmp/rhc_previous_runs
             mv /tmp/rhc/run_* /tmp/rhc_previous_runs
         fi
-        for i in {1..100}
-        do
-            if ! [ -d /tmp/rhc_previous_runs/run_$i ]
-            then
-                mkdir /tmp/rhc/run_$i
-                mv /tmp/rhc/* /tmp/rhc/run_$i
-                break
-            fi
-        done
-        if `ls /tmp/rhc_previous_runs/run_* > /dev/null`
+        if `ls /tmp/rhc/* > /dev/null 2>&1`
+        then
+            for i in {1..100}
+            do
+                if ! [ -d /tmp/rhc_previous_runs/run_$i ]
+                then
+                    mkdir -p /tmp/rhc_previous_runs/run_$i
+                    mv /tmp/rhc/* /tmp/rhc_previous_runs/run_$i
+                    break
+                fi
+            done
+        fi
+        if `ls /tmp/rhc_previous_runs/run_* > /dev/null 2>&1`
         then
             mv /tmp/rhc_previous_runs/run_* /tmp/rhc/
             rm -rf /tmp/rhc_previous_runs
