Making scripts more selinux aware

diff --git a/cartridges/php-5.3.2/info/hooks/configure b/cartridges/php-5.3.2/info/hooks/configure
--- a/cartridges/php-5.3.2/info/hooks/configure
+++ b/cartridges/php-5.3.2/info/hooks/configure
@@ -136,6 +136,7 @@ APP_DIR="$CUSTOMER_HOME/httpd/$application"
 user_id=$(id -u "$customer_id") || error "Could not find user $customer_id" 134
 group_id=$(id -g "$customer_id") || error "Could not find user $customer_id" 135
 
+echo $user_id
 
 #
 # Create git app repo
@@ -192,17 +193,13 @@ range_two=$(echo $IP | awk -F\. '{ print $4 }')
 cat <<EOF > "$APP_DIR/${application}_ctl.sh"
 #/bin/bash
 
-export PHPRC="$APP_DIR/conf/php.ini"
+PHPRC="$APP_DIR/conf/php.ini"
 
 if ! [ \$# -eq 1 ]
 then
     echo "Usage: \$0 [start|restart|graceful|graceful-stop|stop]"
     exit 1
 fi
-
-# Verify we are running as system_r:initrc_t.  Should work fine from unconfined
-initrc_t=''
-runcon | grep -q 'system_r:initrc_t:' || initrc_t='runcon -t initrc_t -r system_r'
 
 case "\$1" in
     start)
@@ -211,11 +208,11 @@ case "\$1" in
             echo -n " - Application is disabled" 1>&2
             exit 0
         else
-            $initrc_t runcon -t libra_t -l s$range_one:c$range_two /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/php-5.3.2/info/configuration/etc/conf/httpd.conf -k \$1
+            runcon -t libra_t -l s$range_one:c$range_two /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/php-5.3.2/info/configuration/etc/conf/httpd.conf -k \$1
         fi
     ;;
     restart|graceful|graceful-stop|stop)
-        $initrc_t runcon -t libra_t -l s$range_one:c$range_two /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/php-5.3.2/info/configuration/etc/conf/httpd.conf -k \$1
+        runcon -t libra_t -l s$range_one:c$range_two /usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/php-5.3.2/info/configuration/etc/conf/httpd.conf -k \$1
     ;;
     status)
         echo "Coming soon"
@@ -226,7 +223,7 @@ EOF
 
 chmod +x "$APP_DIR/${application}_ctl.sh" || error "Failed to chmod new application scripts" 122
 chown $user_id.$group_id -R $APP_DIR || error "Failed to chown new application space.  Please contact support" 123
-$APP_DIR/${application}_ctl.sh start || error "Failed to start ${application}" 121
+runcon -t initrc_t -r system_r runuser "$customer_id" "$APP_DIR/${application}_ctl.sh" start || error "Failed to start ${application}" 121
 
 #
 # Create virtualhost definition for apache
