fixing up php hooks

diff --git a/cartridges/php-5.3.2/info/hooks/configure b/cartridges/php-5.3.2/info/hooks/configure
--- a/cartridges/php-5.3.2/info/hooks/configure
+++ b/cartridges/php-5.3.2/info/hooks/configure
@@ -21,11 +21,66 @@
 # Exit on any errors
 set -e
 
+LIBRA_BASE='/var/lib/libra'
+
 function print_help {
     echo "Usage: $0 package-name config-dir"
 
     echo "$0 $@" | logger -p local0.notice -t libra_http_create
     exit 1
+}
+
+function find_open_ip {
+    # Find an open 127.0.x.x address to host application
+    [ -f $LIBRA_CONF/ip_db ] || echo "customer_id,application_name,service_type,port" >> $LIBRA_CONF/ip_db
+    for i in `seq 0 255`
+    do
+        for j in `seq 2 255`
+        do
+            if ! $(grep -q 127.0.$i.$j $LIBRA_CONF/ip_db)
+            then
+                echo 127.0.$i.$j
+                exit
+            fi
+        done
+    done
+}
+
+function take_open_ip {
+    # Writes a new IP to the ip database in $LIBRA_CONF/ip_db
+    # Example: take_open_ip mmcgrath phpmyadmin httpd
+    if ! [ $# -eq 4 ]
+    then
+        echo "Usage: $0 customer_id application_name service_type port"
+        exit 1
+    fi
+    customer_id=$1
+    application_name=$2
+    service_type=$3
+    port=$4
+
+    # if customer, app, service already exists, re-use IP
+    if $( grep -q "$customer_id,$application_name,$service_type" $LIBRA_CONF/ip_db )
+    then
+        echo $(awk -F, "/$customer_id,$application_name,$service_type/"'{ print $1 }' $LIBRA_CONF/ip_db | head -n1)
+    else
+        IP=$(find_open_ip)
+        echo "$IP,$customer_id,$application_name,$service_type,$port" >> $LIBRA_CONF/ip_db
+        echo $IP
+    fi
+}
+
+function create_repo {
+    application="$1"
+    customer_id="$2"
+    CUSTOMER_HOME="${LIBRA_BASE}/${customer_id}"
+    
+    if [ ! -d $CUSTOMER_HOME ]; then echo "ERROR: Customer ${customer_id} not found!  Please create." 1>&2; exit 2; fi
+    
+    GIT_DIR=$CUSTOMER_HOME/git/$application.git
+    mkdir -p $(dirname $GIT_DIR) 2>&1
+    GIT_DIR=$GIT_DIR git init --shared > /dev/null
+    chown $customer_id.$customer_id -R $GIT_DIR
 }
 
 while getopts 'd' OPTION
@@ -38,13 +93,11 @@ do
     esac
 done
 
-customer_id=`basename $2`
-application=`$1`
 
-if ( [ -z "$customer_id" ] || [ -z "$application" ] )
-then
-    print_help
-fi
+[ $# -eq 2 ] || print_help
+
+customer_id=`basename $2`
+application="$1"
 
 CUSTOMER_HOME="$LIBRA_BASE/$customer_id/"
 APP_DIR="$CUSTOMER_HOME/httpd/$application"
@@ -53,7 +106,7 @@ APP_DIR="$CUSTOMER_HOME/httpd/$application"
 # Create git app repo
 #
 
-/usr/local/bin/libra/create_git.sh -c $customer_id -a $application
+create_repo $application $customer_id
 
 cat <<EOF > $CUSTOMER_HOME/git/$application.git/hooks/post-receive
 rm -rf /var/lib/libra/$customer_id/httpd/test/html/*
@@ -109,7 +162,7 @@ then
     echo "Usage: \$0 [start|restart|graceful|graceful-stop|stop]"
     exit 1
 fi
-/usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /etc/libra/httpd.conf -k \$1
+/usr/sbin/httpd -C 'Include $APP_DIR/conf.d/*.conf' -f /usr/libexec/li/cartridges/php-5.3.2/info/configuration/etc/conf/httpd.conf -k \$1
 EOF
 
 chmod +x "$APP_DIR/${application}_ctl.sh"
@@ -136,4 +189,4 @@ EOF
 
 /sbin/service httpd configtest 2> /dev/null && /sbin/service httpd graceful
 
-/usr/local/bin/libra/update-ddns.sh -h ${application}.${customer_id} -d libra.mmcgrath.net -i $(/usr/bin/facter ipaddress)
+#/usr/local/bin/libra/update-ddns.sh -h ${application}.${customer_id} -d libra.mmcgrath.net -i $(/usr/bin/facter ipaddress)
