added node.conf bits

diff --git a/cartridges/li-controller-0.1/info/hooks/configure b/cartridges/li-controller-0.1/info/hooks/configure
--- a/cartridges/li-controller-0.1/info/hooks/configure
+++ b/cartridges/li-controller-0.1/info/hooks/configure
@@ -21,7 +21,18 @@
 # Exit on any errors
 set -e
 
-LIBRA_BASE='/var/lib/libra'
+if [ -f '/etc/libra/node.conf' ]
+then
+    . /etc/libra/node.conf
+elif [ -f 'node.conf' ]
+    . node.conf
+else
+    echo "node.conf not found.  Cannot continue" 1>&2
+    exit 3
+fi
+
+
+LIBRA_BASE=libra_dir
 
 function print_help {
     echo "Usage: $0"
diff --git a/cartridges/li-controller-0.1/info/hooks/pre-install b/cartridges/li-controller-0.1/info/hooks/pre-install
--- a/cartridges/li-controller-0.1/info/hooks/pre-install
+++ b/cartridges/li-controller-0.1/info/hooks/pre-install
@@ -21,6 +21,18 @@
 # Exit on any errors
 set -e
 
+if [ -f '/etc/libra/node.conf' ]
+then
+    . /etc/libra/node.conf
+elif [ -f 'node.conf' ]
+    . node.conf
+else
+    echo "node.conf not found.  Cannot continue" 1>&2
+    exit 3
+fi
+
+LIBRA_BASE=libra_dir
+
 function print_help {
     echo "Usage: $0 customername"
     exit 1
@@ -39,4 +51,4 @@ then
 fi
 
 groups "$customer_id" > /dev/null 2>&1 && quit "Customer $customer_id already exists"
-[ -d "/var/lib/libra/${customer}" ] || quit "Customer namespace already exists!"
+[ -d "$LIBRA_BASE/${customer}" ] || quit "Customer namespace already exists!"
