jenkins cleanup

diff --git a/cartridges/jenkins-1.4/info/hooks/configure b/cartridges/jenkins-1.4/info/hooks/configure
--- a/cartridges/jenkins-1.4/info/hooks/configure
+++ b/cartridges/jenkins-1.4/info/hooks/configure
@@ -224,10 +224,25 @@ create_repo $application $user_id $group_id $mcs_level
 #
 IP=$(find_open_ip $uid $uuid)
 
-cp $CART_INFO_DIR/bin/app_ctl_wrapper.sh $APP_DIR/${application}_ctl.sh
+#
+# Create simple application start / stop script
+#
+echo "Creating ${application}_ctl.sh..."
+cat <<__EOF__ > "$APP_DIR/${application}_ctl.sh"
+#!/bin/bash -e
+# Import Environment Variables
+for f in ~/.env/*
+do
+    . \$f
+done
+
+app_ctl.sh \$1
+__EOF__
+
+chmod +x "$APP_DIR/${application}_ctl.sh" || error "Failed to chmod new application scripts" 122
 chown $user_id.$group_id -R $APP_DIR || error "Failed to chown new application space.  Please contact support" 123
 # Secure script and config dirs.
-chown root.root "$APP_DIR" $CART_INFO_DIR/bin/app_ctl_wrapper.sh
+chown root.root "$APP_DIR/${application}_ctl.sh" "$APP_DIR"
 chcon -t libra_var_lib_t -l $mcs_level -R "$APP_DIR"
 
 #
