add server identity and namespace auto migrate

diff --git a/node/cartridges/abstract-httpd/info/hooks/update_namespace b/node/cartridges/abstract-httpd/info/hooks/update_namespace
--- a/node/cartridges/abstract-httpd/info/hooks/update_namespace
+++ b/node/cartridges/abstract-httpd/info/hooks/update_namespace
@@ -22,6 +22,17 @@
 set -e
 #set -x
 
+if [ -f '/etc/libra/node.conf' ]
+then
+    . /etc/libra/node.conf
+elif [ -f 'node.conf' ]
+then
+    . node.conf
+else
+    echo "node.conf not found.  Cannot continue" 1>&2
+    exit 3
+fi
+
 function print_help {
     echo "Usage: $0 app-name new_namespace old_namespace uuid"
 
@@ -50,15 +61,12 @@ old_namespace=`basename $3`
 application="$1"
 uuid=$4
 
-if [ -f '/etc/libra/node.conf' ]
+APP_HOME="$libra_dir/$uuid/"
+APP_DIR="$APP_HOME/$application"
+
+if [ ! -d "$APP_DIR" ]
 then
-    . /etc/libra/node.conf
-elif [ -f 'node.conf' ]
-then
-    . node.conf
-else
-    echo "node.conf not found.  Cannot continue" 1>&2
-    exit 3
+  exit 125
 fi
 
 mv_symlink $old_namespace $new_namespace $application
