Added check for overriding aliases

diff --git a/node/cartridges/abstract/info/hooks/add-alias b/node/cartridges/abstract/info/hooks/add-alias
--- a/node/cartridges/abstract/info/hooks/add-alias
+++ b/node/cartridges/abstract/info/hooks/add-alias
@@ -49,6 +49,12 @@ source ${CART_DIR}/li-controller/info/lib/apache
 setup_basic_hook "$1" $2 $3
 server_alias_name="$4"
 
+if grep -q "ServerAlias ${server_alias_name}" /etc/httpd/conf.d/libra/*/server_alias-*.conf
+then
+    echo "CLIENT_ERROR: FATAL ERROR: ${server_alias_name} Already exists."
+    exit 2
+fi
+
 cat <<EOF > "/etc/httpd/conf.d/libra/${uuid}_${namespace}_${application}/server_alias-${server_alias_name}.conf"
 ServerAlias ${server_alias_name}
 EOF
